### ISSUE TITLE
You read my mind

### ISSUE THREAD

**Issue by talamaska** [ihabsoliman/Bootstrap-Form-Builder#1]
I was just wandering did someone already did that rewrite, and i was gonna start to do it.
Thanks a lot.
There is only one issue for me, it seems hard to place the element over the drop zone, can you make it bigger?

**Comment by ihabsoliman** [comment]
Yeah, I am fixing this part

**Comment by ihabsoliman** [comment]
I could use some help fixing the drag and drop and the height part

**Comment by ihabsoliman** [comment]
Fixed
