### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by IonicaBizau** [ihabsoliman/Bootstrap-Form-Builder#11]
I built the BS4 version here: https://github.com/Bloggify/bootstrap-form-builder
Live: https://bloggify.github.io/bootstrap-form-builder/

Hope you will enjoy it and it will be helpful.

Thanks for the amazing work! 
Happy holidays!

**Comment by ihabsoliman** [comment]
Thanks, going to put that in the README
