### ISSUE TITLE
Add possiblity to copy created input text element

### ISSUE THREAD

**Issue by zbindenren** [ihabsoliman/Bootstrap-Form-Builder#3]
Hi

I am using angular and bootstrap and this tool to create the forms. What would be great is the possibility to clone/copy a created input filed. Because I use angular translate I have input files with name like {{'EMAIL' | translate}} etc. That would save me some time.

BR, Rene

**Comment by ihabsoliman** [comment]
I don't see the use of it that much, But you can add this functionality for your own fork
