### ISSUE TITLE
Syntax errors in the yaml files --> ../assets/js/data/yaml

### ISSUE THREAD

**Issue by peterb-2795** [ihabsoliman/Bootstrap-Form-Builder#4]
When exec'ing the parse.rb ruby file, it raises a number of syntax errors in the yaml files.  I have been through these files and fixed them (as I am adding further options).  How do I upload the original files with the fixes applied?

Regards,
Peter

PS:  Thank you for a great piece of work (original author and yourself).  Its a neat little tool for form code generation and has already saved me a bucket of time... kudos guys..

**Comment by ihabsoliman** [comment]
Hey Thanks,
Just do a pull request and I will merge it
